version: '3.8'

services:
  redis:
    image: redis:7
    container_name: scraperq-redis
    ports:
      - "6380:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:17
    container_name: scraperq-postgres
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  redis_data:
  pg_data: